Wikia/react-common

source/components/GlobalNavigation/components/GlobalNavigationNotifications/Card.js
source/components/GlobalNavigation/components/GlobalNavigationNotifications/MarkAsReadIcon.js
source/components/GlobalNavigation/components/GlobalNavigationSearch/GlobalNavigationSearch.js
source/components/GlobalNavigation/index.js

I've moved some methods because of `sort-comp` lint rule.
most important stuff happens in `GlobalNavigation/index.js` and `renderInput` of `Search`.
https://wikia-inc.atlassian.net/browse/IW-1656
@Wikia/iwing

 IW-1632 | add expandable search on mid resolutions

---

source/components/GlobalNavigation/components/GlobalNavigationLink/GlobalNavigationLinkText.js
source/components/GlobalNavigation/components/PartnerSlot/PartnerSlot.js
source/components/GlobalNavigation/index.js

https://wikia-inc.atlassian.net/browse/IW-1631
@Wikia/iwing

IW-1631 | add partner slot

---

source/components/GlobalNavigation/components/GlobalNavigationSearch/GlobalNavigationSearch.js
source/components/GlobalNavigation/components/GlobalNavigationUser/GlobalNavigationUserAnon.js
source/components/GlobalNavigation/index.js

https://wikia-inc.atlassian.net/browse/IW-1634
@Wikia/iwing 
Added missing labels + basic onClick handler for it

IW-1634 | update tracking

---

source/components/GlobalNavigation/components/Link/LinkButton.spec.js
source/components/GlobalNavigation/components/Link/LinkGroup.spec.js
source/components/GlobalNavigation/components/Link/LinkLogOut.js
source/components/GlobalNavigation/components/Link/LinkLogOut.spec.js
source/components/GlobalNavigation/components/Link/LinkText.spec.js
source/components/GlobalNavigation/components/Link/__snapshots__/LinkButton.spec.js.snap
source/components/GlobalNavigation/components/Link/__snapshots__/LinkGroup.spec.js.snap
source/components/GlobalNavigation/components/Link/__snapshots__/LinkLogOut.spec.js.snap
source/components/GlobalNavigation/components/Link/__snapshots__/LinkText.spec.js.snap

https://wikia-inc.atlassian.net/browse/IW-1657
@Wikia/iwing

IW-1657 | add tests for Link components

---

source/components/GlobalNavigation/components/User/MobileAnon.js
source/components/GlobalNavigation/components/User/MobileAnon.spec.js
source/components/GlobalNavigation/components/User/MobileLoggedIn.spec.js
source/components/GlobalNavigation/components/User/MobileUser.spec.js
source/components/GlobalNavigation/components/User/User.spec.js
source/components/GlobalNavigation/components/User/UserAnon.js
source/components/GlobalNavigation/components/User/UserAnon.spec.js
source/components/GlobalNavigation/components/User/UserLoggedIn.js
source/components/GlobalNavigation/components/User/UserLoggedIn.spec.js
source/components/GlobalNavigation/components/User/UserModal.spec.js
source/components/GlobalNavigation/components/User/__snapshots__/MobileAnon.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/MobileLoggedIn.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/MobileUser.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/User.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/UserAnon.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/UserLoggedIn.spec.js.snap
source/components/GlobalNavigation/components/User/__snapshots__/UserModal.spec.js.snap
source/package.json
source/yarn.lock

https://wikia-inc.atlassian.net/browse/IW-1657
@Wikia/iwing 
I've also added missing params for `getRedirectUrl` method

IW-1657 | add tests for User components

---

config/styleguide.config.js
config/styleguide.config.json
package.json
scripts/generate-icons-demo.js
source/icons/demo.md

Generate better demo pages for icons
https://www.dropbox.com/s/qq2xg44rvsq31ii/Screenshot%202019-02-20%2016.15.31.png?dl=0
/cc @JoshuaRogan

Add icons demo

---

package.json

This should fix @JoshuaRogan your issue

Add theme/ and hooks/ to package.json

---

.eslintignore
.gitignore
config/config.js
package.json
scripts/clean.js

Add utils/ to export
Fix missing theme/generateTheme.js
Fix clean script

Add utils exports

---

source/theme/colors.js

Revert colors for now

---

source/theme/colors.js

Revert "Revert colors for now"

---

source/utils/config.js

Causing a build error due to window not being defined. It looks like it would work but it doesn't.

:bug: Not sure why this doesn't work

---

config/styleguide.config.json

- Actually we might want to display it to the users

:bug: Add utils/environment to styleguide

---

.eslintrc
source/components/Countdown/README.md
source/components/Countdown/__snapshots__/index.spec.js.snap
source/components/Countdown/index.js
source/components/Countdown/index.spec.js
source/components/Countdown/styles.scss
source/components/StyledCountdown/README.md
source/components/StyledCountdown/__snapshots__/index.spec.js.snap
source/components/StyledCountdown/index.js
source/components/StyledCountdown/index.spec.js

CAKE-4778 | :sparkles: Component and StyledComponent now supports `stop` prop.

---

source/components/Avatar/README.md
source/components/Avatar/__snapshots__/index.spec.js.snap
source/components/Avatar/index.js
source/components/Avatar/index.spec.js
source/components/AvatarStack/README.md
source/components/AvatarStack/__snapshots__/index.spec.js.snap
source/components/AvatarStack/index.js

- Add `userId` to the `components/Avatar`
- this allows `components/Avatar` to be used by Quiz integration in fepo

:sparkles: Add userId to Avatar component

---

source/components/StyledCountdown/index.js

:bug: Reset timer on OnTick change

---

package.json
source/components/GlobalNavigation/components/Notifications/CardText.js
source/components/GlobalNavigation/components/Notifications/CardText.spec.js
source/components/GlobalNavigation/components/Notifications/MarkAsReadIcon.js
source/components/GlobalNavigation/components/Notifications/NotificationsDataProvider.js
source/components/GlobalNavigation/components/Notifications/__snapshots__/CardText.spec.js.snap
source/components/GlobalNavigation/models/Notification.js
source/components/GlobalNavigation/models/Notification.spec.js
source/components/GlobalNavigation/models/notificationTypes.js
source/components/GlobalNavigation/utils/NotificationsApi.js
source/components/Timeago/__snapshots__/index.spec.js.snap
yarn.lock

Ticket: https://wikia-inc.atlassian.net/browse/IW-2180
/cc @Wikia/iwing

IW-2180 add support for atMentions in on-site-notifications I

---

source/components/StyledArticleTagsSelector/AddedTags.js
source/components/StyledArticleTagsSelector/AddedTags.spec.js
source/components/StyledArticleTagsSelector/SearchForm.spec.js
source/components/StyledArticleTagsSelector/SearchInput.js
source/components/StyledArticleTagsSelector/SearchInput.spec.js
source/components/StyledArticleTagsSelector/SuggestedTags.js
source/components/StyledArticleTagsSelector/SuggestedTags.spec.js
source/components/StyledArticleTagsSelector/TagShape.js
source/components/StyledArticleTagsSelector/__snapshots__/AddedTags.spec.js.snap
source/components/StyledArticleTagsSelector/__snapshots__/SearchForm.spec.js.snap
source/components/StyledArticleTagsSelector/__snapshots__/SearchInput.spec.js.snap
source/components/StyledArticleTagsSelector/__snapshots__/SuggestedTags.spec.js.snap
source/components/StyledArticleTagsSelector/__snapshots__/index.spec.js.snap
source/components/StyledArticleTagsSelector/index.js
source/components/StyledArticleTagsSelector/index.spec.js

Having to handle conversions between id and title is pretty cumbersome. We still will have to convert the relative URL to a full URL when using this component. 
@Wikia/cake

:bug: Use proper object

---

source/utils/environment.js

Attempting to import `lodash` specifically rather that calling the entire library.

cake-5067 | Update lodash import

---

source/components/StyledDropdown/__snapshots__/index.spec.js.snap
source/components/StyledDropdown/index.js

This reverts commit 8686c942222c8c7035404b0c71f0b5fc1ff5a022.

Revert "cake-5090 | Adding spacing between dropdown and text"

---

source/components/Input/index.js

:bug: Fix input class bug

---

source/components/Dropdown/README.md
source/components/Dropdown/components/DropdownToggle/__snapshots__/index.spec.js.snap
source/components/Dropdown/components/DropdownToggle/index.js
source/components/Dropdown/components/DropdownToggle/index.spec.js

Added support for the **More** button icon to Dropdown component.

Add More Button to Dropdown Component

---

config/styleguide.config.json
source/components/Radio/README.md
source/components/Radio/__snapshots__/index.spec.js.snap
source/components/Radio/index.js
source/components/Radio/index.spec.js
source/components/Radio/styles.scss
source/components/RadioGroup/README.md
source/components/RadioGroup/__snapshots__/index.spec.js.snap
source/components/RadioGroup/index.js
source/components/RadioGroup/index.spec.js
source/components/RadioGroup/styles.scss
yarn.lock

https://wikia-inc.atlassian.net/browse/IW-4130
We didn't have a Radio component before, so I decided to add it to this library. I decided to include another component that will group radio buttons together + it will be semantically correct.
What I basically did is I've copied `Checkbox` component and adjusted some parts to `input[type=radio]` shape.

IW-4130 | Radio and RadioGroup components

---

source/components/Radio/__snapshots__/index.spec.js.snap
source/components/Radio/index.js
source/components/Radio/styles.scss

IW-4130 Update styles for radio

---

source/components/GlobalFooter/components/LinkImage.js

https://wikia-inc.atlassian.net/browse/IW-2639
- vkontakte icon added

IW-2639 | fix design system elements for ru wikis

---

source/components/GlobalNavigation/components/Notifications/CardText.js
source/components/GlobalNavigation/components/Notifications/__snapshots__/CardText.spec.js.snap

Use [Trans](https://react.i18next.com/latest/trans-component#using-for-less-than-br-greater-than-and-other-simple-html-elements-in-translations-v-10-4-0) component to handle basic inline styles.

MAIN-22538 | Wrap text in Trans component

---

docs/INSTALLATION.md

Update installation docs

---

package.json
source/components/GlobalNavigation/components/Search/Search.js
source/components/GlobalNavigation/components/Search/Search.spec.js
source/components/GlobalNavigation/components/Search/__snapshots__/Search.spec.js.snap
source/components/GlobalNavigation/index.js

https://wikia-inc.atlassian.net/browse/SITE-582

SITE-582 | opening search suggestions in a new tab is broken

---

source/utils/eventLogger.js

decommissioned error logger
